my_document = open('test5.2.txt', 'r')
content = my_document.read()
print(f'Общее содержимое файла: \n {content}')
my_document = open('test5.2.txt', 'r')
content = my_document.readlines()
print(f'Количество строк: {len(content)}')
my_document = open('test5.2.txt', 'r')
content = my_document.readlines()
for i in range(len(content)):
    print(f'количество символов: {i + 1}-ой строки {len(content[i])}')
my_document = open('test5.2.txt', 'r')
content = my_document.read()
content = content.split()
print(f'количество слов: {len(content)}')
my_document.close()